spring:
  application:
    name: springboot

  datasource:
    url: jdbc:mysql://localhost:3306/coztion?serverTimeZone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml